version: "3"
services:
  db:
    image: postgres:latest
    #    network_mode: bridge
    container_name: db
    #    volumes:
    #      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=del
      - POSTGRES_PASSWORD=qqq
    restart: unless-stopped
  # APP*****************************************
  socks-app:
    build: ./raiffeisen-challenge
    #    network_mode: bridge
    container_name: socks-app
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/del
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qqq
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
